baseURL: https://qige.me
title: QiGe's Blog
theme: PaperMod
searchHidden: true
# uglyURLs: true
defaultContentLanguage: en
languages:
  cn:
    disabled: false
    languageCode: cn-ZH
    languageDirection: ltr
    languageName: Chinese
    params:
      subtitle: 技术，教程，区块链，去中心化金融
    title: 七哥的IT技术博客
    weight: 1
  en:
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Technology, Tutorials, Blockchain, DeFi
    title: QiGe's Blog
    weight: 2

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    lineNos: true
    # style: monokai

services:
  disqus:
    shortname: https-qige-me

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  hideFooter: false
  displayFullLangName: true
  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  label:
    icon: https://img.learnblockchain.cn/7g/202409191616277.png
    iconHeight: 35

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://img.learnblockchain.cn/7g/202409191616937.png"
    favicon16x16: "https://img.learnblockchain.cn/7g/202409191616937.png"
    favicon32x32: "https://img.learnblockchain.cn/7g/202409191616892.png"
    apple_touch_icon: "https://img.learnblockchain.cn/7g/202409191616277.png"
    safari_pinned_tab: "https://img.learnblockchain.cn/7g/202409191616277.png"

  socialIcons:
    - name: x
      url: "https://x.com/0xqige"
    - name: github
      url: "https://github.com/0xqige"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
