main:
  - identifier: categories
    name: Categories
    url: /categories/
    weight: 10
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 20
  - identifier: search
    name: Search
    url: /search/
    weight: 1
  - identifier: about
    name: About
    url: /about
    weight: 40
  # - identifier: example
  #   name: example.org
  #   url: https://example.org
  #   weight: 30
