main:
  - identifier: categories
    name: 分类
    url: /categories/
    weight: 10
  - identifier: tags
    name: 标签
    url: /tags/
    weight: 20
  - identifier: search
    name: 搜索
    url: /search/
    weight: 1
  - identifier: about
    name: 关于
    url: /about/
    weight: 30

  # - identifier: example
  #   name: example.org
  #   url: https://example.org
  #   weight: 30
