env: production # to enable google analytics, opengraph, twitter-cards and schema.
title: 七哥的博客
description: "七哥的博客"
keywords: [Blog, Portfolio, qige.eth, defi]
author: 七哥
# author: ["Me", "You"] # multiple authors
images: ["twitter:image"]
DateFormat: "2006 年 1 月 2 日"

label:
  text: "首页"

# profile-mode
profileMode:
  enabled: true # needs to be explicitly set
  title: "七哥的 IT 技术博客"
  subtitle: "离相寂灭，即是如来"
  imageUrl: "https://img.learnblockchain.cn/7g/202409190046635.jpg"
  imageWidth: 120
  imageHeight: 120
  imageTitle: my image
  buttons:
    - name: 博文
      url: posts
    - name: 标签
      url: tags

# home-info mode
# homeInfoParams:
#   Title: "Hi there \U0001F44B"
#   Content: 欢迎来到我的博客

editPost:
  URL: "https://github.com/0xqige/0xqige/content"
  Text: "编辑" # edit text
  appendFilePath: true # to append file path to Edit link
